# Generated by Django 4.2.5 on 2023-11-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_userid",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="You can get this bot @userinfobot to get your userID",
                null=True,
                unique=True,
                verbose_name="Telegram user ID",
            ),
        ),
    ]
