# Generated by Django 4.2.5 on 2023-09-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created'], 'verbose_name': 'Account'},
        ),
        migrations.AlterModelOptions(
            name='account_type',
            options={'ordering': ['title'], 'verbose_name': 'Type'},
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account_type', verbose_name='Type'),
        ),
    ]
