# Generated by Django 4.2.5 on 2023-09-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options_alter_account_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='start value'),
        ),
    ]
