# Generated by Django 4.2.5 on 2023-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="start value"
            ),
        ),
    ]
