# Generated by Django 4.2.5 on 2023-10-18 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_remove_expenseitem_date_alter_expenseitem_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenseitem",
            name="category",
        ),
    ]
