# Generated by Django 4.2.5 on 2023-10-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transaction_type"),
        ("budget", "0003_remove_expenseitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseitem",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.category",
            ),
            preserve_default=False,
        ),
    ]
