# Generated by Django 4.2.5 on 2023-11-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
        ("budget", "0003_alter_incomeitem_budget_alter_incomeitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="currency.currency",
            ),
            preserve_default=False,
        ),
    ]
