# Generated by Django 4.2.5 on 2023-10-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transaction_type"),
        ("budget", "0004_expenseitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseitem",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="expenseitem",
            unique_together={("category", "budget")},
        ),
    ]
