# Generated by Django 4.2.5 on 2023-10-20 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0005_alter_expenseitem_description_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expenseitem",
            unique_together=set(),
        ),
    ]
