# Generated by Django 4.2.5 on 2023-10-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0006_alter_expenseitem_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseitem",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_items",
                to="budget.budget",
            ),
        ),
    ]
