# Generated by Django 4.2.5 on 2023-10-20 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transaction_type"),
        ("budget", "0007_alter_expenseitem_budget"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="expenseitem",
            unique_together={("category", "budget")},
        ),
    ]
