# Generated by Django 4.2.5 on 2023-11-23 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_budget_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"ordering": ["title"]},
        ),
    ]
