# Generated by Django 4.2.5 on 2023-11-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0002_transaction_account_from_transaction_account_to_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="account_from",
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_converted",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_converted_to",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
