# Generated by Django 4.2.5 on 2023-12-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_remove_transaction_account_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
