# Generated by Django 4.2.5 on 2023-12-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_category_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_type",
            name="type",
            field=models.CharField(
                choices=[("+", "Income"), ("-", "Expense"), ("=", "Transfer")],
                default="-",
                max_length=1,
                unique=True,
            ),
        ),
    ]
