# Generated by Django 4.2.5 on 2023-12-24 08:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_alter_category_title_alter_category_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="isTransfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_group_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
