# Generated by Django 4.2.5 on 2023-09-06 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transaction_type',
            options={'ordering': ['title'], 'verbose_name': 'Type'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction_type', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_expense', to=settings.AUTH_USER_MODEL, verbose_name='Who'),
        ),
    ]
