# Generated by Django 4.2.5 on 2023-09-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_type',
            name='type',
            field=models.CharField(choices=[('+', 'Income'), ('-', 'Expense')], default='-', max_length=1),
        ),
    ]
