# Generated by Django 4.2.5 on 2023-10-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
