# Generated by Django 4.2.5 on 2023-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_alter_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
